hyperparameters = {
    "seed": 42,
    #   "fast": false,
    #   "mixup": false,
    #   "balance": false,
    #   "balance_datasets": false,
    #   "swa": false,
    #   "show": false,
    #   "use_idrid": false,
    #   "use_messidor": false,
    #   "use_aptos2015": false,
    # "use_aptos2019": "",
    # "verbose": "",
    #   "coarse": false,
    "accumulation_steps": 1,
    "data_dir": "/opt/ml/input/data",
    "model": "seresnext50d_gwap",
    "batch_size": 64,
    "epochs": 200,
    "early_stopping": 10,
    # "fold": [
    #     0,
    #     1,
    #     2,
    #     3
    # ],
    #   "freeze_encoder": false,
    "learning_rate": 0.0003,
    # "criterion_reg": [
    #     "mse"
    # ],
    #   "criterion_ord": null,
    # "criterion_cls": [
    #     "focal_kappa"
    # ],
    "l1": 0.0002,
    "l2": 0,
    "optimizer": "AdamW",
    #   "preprocessing": null,
    #   "checkpoint": null,
    #   "workers": 64,
    "augmentations": "medium",
    #   "tta": null,
    #   "transfer": null,
    #   "fp16": true,
    "scheduler": "multistep",
    "size": 1024,
    "weight_decay": 0.0001,
    #   "weight_decay_step": null,
    "dropout": 0.0,
    "warmup": 0,
    #   "experiment": null
}
